# Generated by Django 4.1.1 on 2022-09-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='Blog Thumbnail'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(verbose_name='Enter Comment'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content',
            field=models.TextField(verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_slug',
            field=models.SlugField(max_length=264, unique=True, verbose_name='Blog Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Blog Title'),
        ),
    ]
